// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accommodation_info: dynamic(() => import("./AccommodationInfo")),
  event_program: dynamic(() => import("./EventProgram")),
  message_card: dynamic(() => import("./MessageCard")),
  my_own_creations: dynamic(() => import("./MyOwnCreations")),
  registration_state: dynamic(() => import("./RegistrationState")),
};
